console.log(Portland High School Graduation Rate.);
High Schools: {
	schools: {
		2015_Class_Size:98,
		Percent_On_Time_Grads:13,
		Number_of_Dropouts:40,
		School_Name:'Alliance'
	},
	{
		2015_Class_Size:190,
		Percent_On_Time_Grads:88,
		Number_of_Dropouts:12,
		School_Name:'Benson'		
	},
	{
		2015_Class_Size:384,
		Percent_On_Time_Grads:85,
		Number_of_Dropouts:36,
		School_Name:'Cleveland'		
	},
	{
		2015_Class_Size:413,
		Percent_On_Time_Grads:88,
		Number_of_Dropouts:32,
		School_Name:'Franklin'		
	},	
	{
		2015_Class_Size:387,
		Percent_On_Time_Grads:89,
		Number_of_Dropouts:21,
		School_Name:'Grant'		
	},	
	{
		2015_Class_Size:128,
		Percent_On_Time_Grads:80,
		Number_of_Dropouts:13,
		School_Name:'Jefferson'		
	},
	{
		2015_Class_Size:98,
		Percent_On_Time_Grads:26,
		Number_of_Dropouts:53,
		School_Name:'Leadership & Entrepreneurship Public Charter'		
	},	
	{
		2015_Class_Size:383,
		Percent_On_Time_Grads:93,
		Number_of_Dropouts:17,
		School_Name:'Lincoln'		
	},
	{
		2015_Class_Size:263,
		Percent_On_Time_Grads:74,
		Number_of_Dropouts:41,
		School_Name:'Madison'		
	},	
	{
		2015_Class_Size:32,
		Percent_On_Time_Grads:72,
		Number_of_Dropouts:5,
		School_Name:'Metropolitan Learning Center'		
	},	
	{
		2015_Class_Size:240,
		Percent_On_Time_Grads:62,
		Number_of_Dropouts:52,
		School_Name:'Roosevelt'		
	},		
		{
		2015_Class_Size:15,
		Percent_On_Time_Grads:40,
		Number_of_Dropouts:4,
		School_Name:'Trillium'		
	},	
	{
		2015_Class_Size:301,
		Percent_On_Time_Grads:91,
		Number_of_Dropouts:25,
		School_Name:'Wilson'		
	}	
}
